server:
    port: 8080
    context-path: #/liuzh/

name: helloworld
my:
    secret: ${random.value}
    number: ${random.int}

logging:
    level:
        tk.mybatis: DEBUG


spring:
    jpa:
        hibernate:
            #允许在数据库中表不存在情况下,hibernate根据Entity中的关系,创建数据库表
            ddl-auto: update
        show-sql: true
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/springd?useUnicode=true&characterEncoding=UTF-8
        username: root
        password:
        driverClassName: com.mysql.jdbc.Driver
    mvc:
        view:
            prefix: /views/
            suffix: #.jsp